[package]
name = "m4arch-gui"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
iced = { version = "0.12", features = ["debug", "tokio"] }
m4arch-core = { path = "../m4arch-core" }
m4arch-service = { path = "../m4arch-service" }
